#!/usr/bin/env bash
# install an nginx web server w/ a script!
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
echo "Holberton School for the win!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
