#!/usr/bin/env bash
#install an nginx web server w/ a script!
#extra line
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" >> /var/www/html/index.nginx-debian.html
sudo service nginx start
