#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
sudo sed -i "/^\tlocation \// i\ \tlocation /redirect_me {\n\t\treturn 301 https://www.yo\
utube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx reload
