#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string
# Ceci n'est pas une page.
sudo apt-get update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
find_string="#error_page 404 /404.html;"
replace_string="error_page 404 /custom_404.html;\n location = /custom_404.html {\n root /usr/share/nginx/html;\n internal;\n}"
sudo sed -i "s@$find_string@$replace_string@" /etc/nginx/sites-available/default
sudo service nginx restart
