#!/usr/bin/env bash
# installs nginx, manages: index.html, 404-error, redirect_me & custom headers
# shellcheck disable=SC2154

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo touch /var/www/html//reeses-404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/reeses-404.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a error_page 404 /reeses-404.html;' /etc/nginx/sites-available/default

sudo sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

service nginx restart
