#!/usr/bin/env bash
# loops from 1 -10 with diferent displays

x=0
while [ $x -lt 10 ]
do
    ((x++))
    if [ $x -eq 4 ]
    then
	echo "bad luck"
    elif [ $x -eq 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
done
