#!/usr/bin/env bash
# displays numbers from 1 to 20 with some exceptions

x=1
while [ $x -le 20 ]
do
    case $x in
	5) echo "bad luck from China";;
	10) echo "bad luck from Japan";;
	18) echo "bad luck form Italy";;
    esac
    echo "$x"
    ((x++))
done
