#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

x=0

while [ $x -lt 13 ]
do
    echo "Hour: $x"
    y=1
    while [ $y -lt 60 ]
    do
	echo "$y"
	((y++))
    done
    x=$(( x+1 ))
done
